name: Kernel Derleyici (32-bit ARM)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4 # v3'ten v4'e güncellendi

      - name: Bağımlılıkları Kur
        run: |
          sudo apt update
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev gcc-arm-linux-gnueabi

      - name: Derlemeyi Başlat
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          # Klasördeki defconfig adını kontrol et (Örn: msm8917_defconfig veya j6primelte_defconfig)
          make j6primelte_swa_open_defconfig 
          make -j$(nproc)

      - name: Dosyayı Hazırla
        run: |
          mkdir output
          if [ -f arch/arm/boot/zImage-dtb ]; then
            cp arch/arm/boot/zImage-dtb output/
          elif [ -f arch/arm/boot/zImage ]; then
            cp arch/arm/boot/zImage output/
          fi

      - name: Sonucu Yükle
        uses: actions/upload-artifact@v4 # İşte burası v4 olarak güncellendi
        with:
          name: J6-Plus-32Bit-Kernel
          path: output/*
