name: J6-Kernel-Build (Hizli + GCC 4.9)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # En hizli sira gelen surum
    steps:
      - name: Kernel Kodlarini Cek
        uses: actions/checkout@v4

      - name: Eski Derleyiciyi Indir (GCC 4.9)
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git toolchain

      - name: Paketleri ve Python2'yi Yukle
        run: |
          sudo apt update
          # Ubuntu 22.04 icin gerekli tum paketler
          sudo apt install -y build-essential bc libncurses5 libncurses5-dev libssl-dev bison flex libelf-dev python2
          
          # Python komutunu Python2'ye yonlendiriyoruz (Kernel icin sart)
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Derlemeyi Baslat
        run: |
          export ARCH=arm
          # Indirdigimiz ozel derleyiciyi kullaniyoruz
          export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchain/bin/arm-linux-androideabi-
          
          make j6primelte_swa_open_defconfig
          
          # Derleme baslasin
          make -j$(nproc)

      - name: Dosyalari Hazirla
        run: |
          mkdir -p output
          if [ -f arch/arm/boot/zImage-dtb ]; then cp arch/arm/boot/zImage-dtb output/; fi
          if [ -f arch/arm/boot/zImage ]; then cp arch/arm/boot/zImage output/; fi

      - name: Sonucu Yukle
        uses: actions/upload-artifact@v4
        with:
          name: J6-Plus-NetHunter-Kernel
          path: output/*
