name: Kernel Derleyici (J6 Plus 32-bit)
on:
  workflow_dispatch: # Manuel başlatmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Bağımlılıkları Kur
        run: |
          sudo apt update
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev gcc-arm-linux-gnueabi

      - name: Derlemeyi Başlat
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          # Senin bulduğun tam dosya adını buraya yazdık:
          make j6primelte_swa_open_defconfig
          make -j$(nproc)

      - name: Dosyayı Hazırla
        run: |
          mkdir output
          # 32-bit ARM çıktısı genellikle zImage veya zImage-dtb olur
          if [ -f arch/arm/boot/zImage-dtb ]; then
            cp arch/arm/boot/zImage-dtb output/
          elif [ -f arch/arm/boot/zImage ]; then
            cp arch/arm/boot/zImage output/
          fi

      - name: Sonucu Yükle
        uses: actions/upload-artifact@v4
        with:
          name: J6-Plus-NetHunter-Kernel
          path: output/*
