name: J6-Kernel-Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Paketleri Yukle
        run: |
          sudo apt update
          # Python2'yi apt üzerinden kuruyoruz
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev gcc-arm-linux-gnueabi python2

      - name: Derlemeyi Baslat
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          
          # Python2 komutunu garantiye alıyoruz (Hatanın çözümü burada)
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          
          # Derleme komutları
          make j6primelte_swa_open_defconfig
          make -j$(nproc) HOSTCFLAGS="-fcommon" HOSTLDFLAGS="-fcommon"

      - name: Dosyalari Hazirla
        run: |
          mkdir -p output
          if [ -f arch/arm/boot/zImage-dtb ]; then cp arch/arm/boot/zImage-dtb output/; fi
          if [ -f arch/arm/boot/zImage ]; then cp arch/arm/boot/zImage output/; fi

      - name: Sonucu Yukle
        uses: actions/upload-artifact@v4
        with:
          name: J6-Plus-Kernel
          path: output/*
