name: Kernel Derleyici (J6 Plus 32-bit - Fix)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Bağımlılıkları Kur
        run: |
          sudo apt update
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev gcc-arm-linux-gnueabi python2

      - name: Derlemeyi Başlat
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          make j6primelte_swa_open_defconfig
          make -j$(nproc) HOSTCFLAGS="-fcommon" HOSTLDFLAGS="-fcommon"

      - name: Dosyayı Hazırla
        run: |
          mkdir output
          if [ -f arch/arm/boot/zImage-dtb ]; then
            cp arch/arm/boot/zImage-dtb output/
          elif [ -f arch/arm/boot/zImage ]; then
            cp arch/arm/boot/zImage output/
          fi

      - name: Sonucu Yükle
        uses: actions/upload-artifact@v4
        with:
          name: J6-Plus-NetHunter-Kernel
          path: output/*
