name: J6-Kernel-Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '2.7'

      - name: Paketleri Yukle
        run: |
          sudo apt update
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev gcc-arm-linux-gnueabi

      - name: Derle
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python
          make j6primelte_swa_open_defconfig
          make -j$(nproc) HOSTCFLAGS="-fcommon" HOSTLDFLAGS="-fcommon"

      - name: Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Dosyasi
          path: arch/arm/boot/zImage*
          mkdir output
          if [ -f arch/arm/boot/zImage-dtb ]; then
            cp arch/arm/boot/zImage-dtb output/
          elif [ -f arch/arm/boot/zImage ]; then
            cp arch/arm/boot/zImage output/
          fi

      - name: Sonucu Yükle
        uses: actions/upload-artifact@v4
        with:
          name: J6-Plus-NetHunter-Kernel
          path: output/*
          name: J6-Plus-NetHunter-Kernel
          path: output/*
